spring.application.name=wallet-app

spring.datasource.url=jdbc:postgresql://localhost:5433/wallet_db
spring.datasource.username=wallet_admin
spring.datasource.password=admin5656
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
server.port=8082
jwt.secret=bE5AC5OdmRkbCc9bYe1ReSmA0ShJNTz6SSJLBQTwbQA=
jwt.expiration-ms=86400000